# Generated by Django 3.2.7 on 2022-01-05 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
